#!/bin/bash

cd "$(dirname "$0")"

if [ -r .env ]; then
  . .env
fi

export TZ=EST
thisyear="$(date +%Y)"
thismonth="$(date +%m)"
thisday="$(date +%d)"

mkdir -p input

year=$1
for day in {1..25}; do
  if [ "$thisyear" -ne "$year" -o "$thismonth" -ne 12 -o "$day" -gt "$thisday" ]; then
    exit 0
  fi
  filename="input/day$(printf "%02d" $day)".input
  if [ -r "$filename" ]; then
    continue  # make sure we don't fetch the same file twice!
  fi
  curl -sS -o "$filename" -b "$AOC_SESSION" https://adventofcode.com/"$year"/day/"$day"/input
done
